### PR TITLE
fixing #310

### PR DESCRIPTION
**Pull request by eesha-0705**

### CODE REVIEW

**Comment by russon77** [comment]
@eesha-0705 it looks like you committed a lot of extra build files.. i suggest you remove them before merge.

**Comment by eesha-0705** [comment]
@russon77  - im new to git and would appreciate if you would tell me what files need to be removed.

**Comment by russon77** [comment]
@eesha-0705 i think you only meant to commit the `organization-*` files. the rest should be removed.

**Comment by eesha-0705** [comment]
@russon77 - I checked and the only files i committed are 


C:\Users\eesha.dabral\C4SG>git log --name-only
commit 38f6b0e819f327d0e2252c84085349630478baf7
Author: eesha dev <eesha.dabral@gmail.com>
Date:   Sun Feb 26 22:32:57 2017 -0800

    fixed #310

C4SGWeb/app/organization/common/organization.ts
C4SGWeb/app/organization/list/organization-list.component.css
C4SGWeb/app/organization/list/organization-list.component.html
C4SGWeb/app/organization/list/organization-list.component.ts
C4SGWeb/app/organization/view/organization-view.component.ts



and nothing else. This should be ok to accept the request and accept the changes.

thanks.

**Comment by russon77** [comment]
@eesha-0705 it's this commit

https://github.com/Code4SocialGood/C4SG/pull/347/commits/1793feea605d91eb96f173ffb473192faac72b4c

**Comment by eesha-0705** [comment]
@russon77  -- 56d58f4 this one

**Comment by russon77** [comment]
@eesha-0705 if you go here 

https://github.com/Code4SocialGood/C4SG/pull/347/files

you will see 239 files edited. you may wish to create a new PR. i ran into this problem a lot when i first started on github

**Pull request closed without merging**
